server:
  port: 8089
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.103.214.18:3306/community_management?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql